/**
 * Static content for the Explore and Place Detail screens.
 * Coordinates are real WGS84 positions around Peshawar, Khyber Pakhtunkhwa,
 * and each place's neighbourhood, address and coordinates agree.
 */

/** @type {import('./types').Viewer} */
export const viewer = {
  firstName: 'Adeel',
  city: 'Peshawar',
  circleName: 'Bala Bagh Circle',
  trustScore: 87,
  trustLabel: 'Trusted',
  streakWeeks: 12,
  circles: 6,
  saved: 24,
};

/** @type {import('./types').Greeting} */
export const greeting = {
  eyebrow: 'Good afternoon',
  title: 'Explore Peshawar',
};

/** @type {import('./types').Category[]} */
export const categories = [
  { id: 'all', label: 'All', count: 248 },
  { id: 'food', label: 'Food', count: 96 },
  { id: 'coffee', label: 'Coffee', count: 41 },
  { id: 'hotels', label: 'Hotels', count: 18 },
  { id: 'shopping', label: 'Shopping', count: 57 },
  { id: 'culture', label: 'Culture', count: 22 },
  { id: 'parks', label: 'Parks', count: 14 },
];

/** People in the viewer's trust circle. */
/** @type {import('./types').Member[]} */
export const members = [
  { id: 'm1', name: 'Bilal Ahmad', initials: 'BA', tint: '#a03246', relation: 'Flatmate' },
  { id: 'm2', name: 'Sana Khalid', initials: 'SK', tint: '#4a6b52', relation: 'College friend' },
  { id: 'm3', name: 'Hamza Tariq', initials: 'HT', tint: '#c08a2e', relation: 'Work' },
  { id: 'm4', name: 'Areeba Nawaz', initials: 'AN', tint: '#6e5a86', relation: 'School' },
  { id: 'm5', name: 'Daniyal Shah', initials: 'DS', tint: '#a0695a', relation: 'Cousin' },
  { id: 'm6', name: 'Maryam Iqbal', initials: 'MI', tint: '#d6a59f', relation: 'Society' },
  { id: 'm7', name: 'Usman Ghani', initials: 'UG', tint: '#799b91', relation: 'Team' },
  { id: 'm8', name: 'Fatima Javed', initials: 'FJ', tint: '#be883a', relation: 'Neighbour' },
  { id: 'm9', name: 'Hina Aslam', initials: 'HA', tint: '#9d6b58', relation: 'Batchmate' },
  { id: 'm10', name: 'Zaryab Khan', initials: 'ZK', tint: '#bc7c80', relation: 'Society' },
  { id: 'm11', name: 'Omar Sheikh', initials: 'OS', tint: '#b55e43', relation: 'Cousin' },
  { id: 'm12', name: 'Zainab Tariq', initials: 'ZT', tint: '#cf9f6e', relation: 'Work' },
  { id: 'm13', name: 'Adeel Rehman', initials: 'AR', tint: '#6b7f6b', relation: 'Team' },
  { id: 'm14', name: 'Mahnoor Shah', initials: 'MS', tint: '#c98f7a', relation: 'College friend' },
  { id: 'm15', name: 'Talha Khan', initials: 'TK', tint: '#8f6b8a', relation: 'School' },
  { id: 'm16', name: 'Rabia Noor', initials: 'RN', tint: '#d8a05a', relation: 'Neighbour' },
  { id: 'm17', name: 'Kamran Shah', initials: 'KS', tint: '#5f7f74', relation: 'Flatmate' },
];

/** @type {import('./types').Place[]} */
export const places = [
  {
    id: 'khyber-restaurant',
    name: 'Khyber Restaurant',
    category: 'food',
    categoryLabel: 'Restaurant',
    neighbourhood: 'Saddar Bazaar',
    address: '23 Saddar Bazaar, Peshawar',
    lngLat: [71.556, 34.0085],
    distanceKm: 0.8,
    rating: 4.7,
    reviews: 128,
    priceLevel: '$$',
    openNow: true,
    closesAt: '23:30',
    blurb: 'Charcoal-grilled seekh and mutton karahi that has anchored Saddar for three decades.',
    tags: ['Charcoal grill', 'Family hall', 'Cash only'],
    visitedBy: ['m1', 'm2', 'm5'],
    photos: [
      'khyber-restaurant-hero-1',
      'khyber-restaurant-hero-2',
      'khyber-restaurant-hero-3',
      'khyber-restaurant-hero-4',
    ],
    experiences: [
      {
        id: 'x1',
        authorId: 'm1',
        when: '2 days ago',
        rating: 5,
        body: 'The chapli kebab was exceptional — smoky, generous, and exactly what I hoped for. The room has a lovely old Peshawar warmth too.',
        photo: 'khyber-restaurant-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm2',
        when: '5 days ago',
        rating: 4.5,
        body: 'Went for the seekh kebab and stayed for the mutton karahi. Cash only, so come prepared. Service is unhurried in the best way.',
        photo: 'khyber-restaurant-exp-2',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm5',
        when: '2 weeks ago',
        rating: 4,
        body: 'Consistent rather than exciting, which for this part of town is a compliment. Get there before seven or the family hall takes over.',
        photo: 'khyber-restaurant-exp-3',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
    ],
    seal: 'Circle favourite',
  },
  {
    id: 'beanstalk-coffee',
    name: 'Beanstalk Coffee',
    category: 'coffee',
    categoryLabel: 'Coffee house',
    neighbourhood: 'Hayatabad Phase 1',
    address: '4 Phase 1, Hayatabad, Peshawar',
    lngLat: [71.445, 34.0072],
    distanceKm: 1.2,
    rating: 4.8,
    reviews: 214,
    priceLevel: '$$',
    openNow: true,
    closesAt: '22:00',
    blurb: 'Single-origin pour-overs and a courtyard that stays quiet even at sunset.',
    tags: ['Pour over', 'Work friendly', 'Outdoor'],
    visitedBy: ['m3', 'm6', 'm4'],
    photos: [
      'beanstalk-coffee-hero-1',
      'beanstalk-coffee-hero-2',
      'beanstalk-coffee-hero-3',
      'beanstalk-coffee-hero-4',
    ],
    experiences: [
      {
        id: 'x1',
        authorId: 'm3',
        when: 'Yesterday',
        rating: 5,
        body: 'The washed Ethiopian pour-over is the best cup I have had north of Islamabad. Courtyard seating if you want to sit for a while.',
        photo: 'beanstalk-coffee-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm6',
        when: '4 days ago',
        rating: 4.5,
        body: 'Quiet enough to take a call, which is rarer than it should be. Pastries are still warm around four.',
        photo: 'beanstalk-coffee-exp-2',
        signals: { photo: true, visitDetails: false, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm4',
        when: 'Last week',
        rating: 5,
        body: 'Third visit this month. They rotate the single origin and it keeps getting better.',
        photo: 'beanstalk-coffee-exp-3',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
    ],
    seal: 'Top rated nearby',
  },
  {
    id: 'cheezious-usmanzai',
    name: 'Cheezious',
    category: 'food',
    categoryLabel: 'Fast food',
    neighbourhood: 'Usmanzai',
    address: 'Main Bazaar, Usmanzai, Peshawar',
    lngLat: [71.4822, 33.9956],
    distanceKm: 3.4,
    rating: 4.5,
    reviews: 903,
    priceLevel: '$',
    openNow: true,
    closesAt: '01:00',
    blurb: 'The Zinger legend. Expect a queue after 8pm and worth every minute of it.',
    tags: ['Zinger', 'Late night', 'Takeaway'],
    visitedBy: ['m1', 'm4', 'm7'],
    photos: [
      'cheezious-usmanzai-hero-1',
      'cheezious-usmanzai-hero-2',
      'cheezious-usmanzai-hero-3',
      'cheezious-usmanzai-hero-4',
    ],
    experiences: [
      {
        id: 'x1',
        authorId: 'm7',
        when: '3 days ago',
        rating: 5,
        body: 'Worth every minute of the queue. The Zinger arrives hot, the bun is properly toasted, and the fries survive the walk home.',
        photo: 'cheezious-usmanzai-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm4',
        when: '1 week ago',
        rating: 4,
        body: 'Good, loud, and consistent. Not a place for a quiet conversation.',
        photo: 'cheezious-usmanzai-exp-2',
        signals: { photo: true, visitDetails: false, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm1',
        when: '3 weeks ago',
        rating: 4,
        body: 'They have not missed once. Midnight run after a wedding, exactly as advertised.',
        photo: 'cheezious-usmanzai-exp-3',
        signals: { photo: false, visitDetails: true, confirmed: true },
      },
    ],
    seal: null,
  },
  {
    id: 'qissa-khwani-bazaar',
    name: 'Qissa Khwani Bazaar',
    category: 'shopping',
    categoryLabel: 'Bazaar',
    neighbourhood: 'Qissa Khwani',
    address: 'Qissa Khwani Bazaar, Peshawar',
    lngLat: [71.5625, 34.0128],
    distanceKm: 5.1,
    rating: 4.6,
    reviews: 512,
    priceLevel: '$',
    openNow: true,
    closesAt: '20:30',
    blurb: 'Heddings, copper and dry fruit in the lanes the city has traded in for generations.',
    tags: ['Bargain', 'Heritage', 'Weekends'],
    visitedBy: ['m2', 'm6', 'm8'],
    photos: [
      'qissa-khwani-bazaar-hero-1',
      'qissa-khwani-bazaar-hero-2',
      'qissa-khwani-bazaar-hero-3',
      'qissa-khwani-bazaar-hero-4',
    ],
    experiences: [
      {
        id: 'x1',
        authorId: 'm8',
        when: '4 days ago',
        rating: 5,
        body: 'Go before eleven or you will not get a look. The dry fruit stalls at the far end are the real reason to come.',
        photo: 'qissa-khwani-bazaar-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm2',
        when: '2 weeks ago',
        rating: 4.5,
        body: 'Bargain politely, stay patient, and never show you are in a hurry.',
        photo: 'qissa-khwani-bazaar-exp-2',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm6',
        when: '1 month ago',
        rating: 4,
        body: 'Chaotic and wonderful. Bring cash and a friend who will not get lost.',
        photo: 'qissa-khwani-bazaar-exp-3',
        signals: { photo: false, visitDetails: false, confirmed: true },
      },
    ],
    seal: 'Circle favourite',
  },
  {
    id: 'hotel-shahi',
    name: 'Hotel Shahi',
    category: 'hotels',
    categoryLabel: 'Hotel',
    neighbourhood: 'Circular Road',
    address: 'Circular Road, Cantt, Peshawar',
    lngLat: [71.52, 34.008],
    distanceKm: 2.6,
    rating: 4.3,
    reviews: 347,
    priceLevel: '$$$',
    openNow: false,
    closesAt: 'Reopens 06:00',
    blurb: 'A 1990s circular-road landmark with a bakery that quietly outdraws the lobby.',
    tags: ['Rooms', 'Bakery', 'Conference'],
    visitedBy: ['m7', 'm3', 'm5'],
    photos: [
      'hotel-shahi-hero-1',
      'hotel-shahi-hero-2',
      'hotel-shahi-hero-3',
      'hotel-shahi-hero-4',
    ],
    experiences: [
      {
        id: 'x1',
        authorId: 'm3',
        when: '2 weeks ago',
        rating: 4.5,
        body: 'The rooms are tired and the conference hall is excellent. Breakfast upstairs is the actual reason to stay.',
        photo: 'hotel-shahi-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm7',
        when: '1 month ago',
        rating: 4,
        body: 'Fine for a conference. Ask for a room on the courtyard side.',
        photo: 'hotel-shahi-exp-2',
        signals: { photo: true, visitDetails: false, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm5',
        when: '2 months ago',
        rating: 4,
        body: 'Reliable, unremarkable, and the bakery is worth a detour either way.',
        photo: 'hotel-shahi-exp-3',
        signals: { photo: false, visitDetails: true, confirmed: true },
      },
    ],
    seal: null,
  },
  {
    id: 'bala-bagh-fort',
    name: 'Bala Bagh Fort',
    category: 'culture',
    categoryLabel: 'Heritage',
    neighbourhood: 'Bala Bagh',
    address: 'Bala Bagh, Peshawar',
    lngLat: [71.5825, 34.0175],
    distanceKm: 6.3,
    rating: 4.4,
    reviews: 289,
    priceLevel: 'Free',
    openNow: true,
    closesAt: '18:00',
    blurb: 'Timur-era fort on the highest ground in the city. Go at dusk, when the light turns.',
    tags: ['Heritage', 'Sunset', 'Free entry'],
    visitedBy: ['m4', 'm5', 'm1'],
    photos: [
      'bala-bagh-fort-hero-1',
      'bala-bagh-fort-hero-2',
      'bala-bagh-fort-hero-3',
      'bala-bagh-fort-hero-4',
    ],
    experiences: [
      {
        id: 'x1',
        authorId: 'm1',
        when: 'Yesterday',
        rating: 5,
        body: 'Go at dusk. The light comes through the eastern arch at about half five and the whole city is laid out below you.',
        photo: 'bala-bagh-fort-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm4',
        when: '5 days ago',
        rating: 4.5,
        body: 'Free, quiet, and almost empty in the morning. Carry water — there is nowhere to buy it.',
        photo: 'bala-bagh-fort-exp-2',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm5',
        when: '3 weeks ago',
        rating: 3.5,
        body: 'Historic and worth the climb, though the upkeep is uneven.',
        photo: 'bala-bagh-fort-exp-3',
        signals: { photo: true, visitDetails: false, confirmed: true },
      },
    ],
    seal: null,
  },
  {
    id: 'cafe-qahwa',
    name: 'Café Qahwa',
    category: 'coffee',
    categoryLabel: 'Coffee house',
    neighbourhood: 'University Road',
    address: '18 University Road, Peshawar',
    lngLat: [71.485, 33.9975],
    distanceKm: 3.9,
    rating: 4.6,
    reviews: 176,
    priceLevel: '$',
    openNow: true,
    closesAt: '23:00',
    blurb: 'Student-run roastery doing serious work with washed arabica off the Islamabad road.',
    tags: ['Roastery', 'Beans to cup', 'Quiet'],
    visitedBy: ['m3', 'm2', 'm6'],
    photos: ['cafe-qahwa-hero-1', 'cafe-qahwa-hero-2', 'cafe-qahwa-hero-3', 'cafe-qahwa-hero-4'],
    experiences: [
      {
        id: 'x1',
        authorId: 'm2',
        when: '3 days ago',
        rating: 5,
        body: 'They roast on the back shelf and will talk you through it if you ask. The flat white is properly made, not whipped.',
        photo: 'cafe-qahwa-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm6',
        when: '6 days ago',
        rating: 4,
        body: 'Small and student-run, which means small and inconsistent at peak. Go early.',
        photo: 'cafe-qahwa-exp-2',
        signals: { photo: true, visitDetails: false, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm3',
        when: '2 weeks ago',
        rating: 4.5,
        body: 'Best beans in Peshawar without contest, and they will sell you a bag.',
        photo: 'cafe-qahwa-exp-3',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
    ],
    seal: null,
  },
  {
    id: 'peshawar-museum',
    name: 'Peshawar Museum',
    category: 'culture',
    categoryLabel: 'Museum',
    neighbourhood: 'Bala Bagh',
    address: 'Bala Bagh, Peshawar',
    lngLat: [71.5775, 34.0136],
    distanceKm: 6.1,
    rating: 4.2,
    reviews: 164,
    priceLevel: 'Free',
    openNow: false,
    closesAt: 'Closed Mondays',
    blurb: 'Gandhara Buddhist sculpture and the machinery of the bicycles that built Pakistan.',
    tags: ['Gandhara', 'Guided tour', 'Free entry'],
    visitedBy: ['m6', 'm8', 'm7'],
    photos: [
      'peshawar-museum-hero-1',
      'peshawar-museum-hero-2',
      'peshawar-museum-hero-3',
      'peshawar-museum-hero-4',
    ],
    experiences: [
      {
        id: 'x1',
        authorId: 'm8',
        when: '2 weeks ago',
        rating: 4.5,
        body: 'Ask for the guided tour — an hour is plenty and the Gandhara room alone justifies it. Closed Mondays.',
        photo: 'peshawar-museum-exp-1',
        signals: { photo: true, visitDetails: true, confirmed: true },
      },
      {
        id: 'x2',
        authorId: 'm7',
        when: '1 month ago',
        rating: 4,
        body: 'Free, unhurried, and the bicycle gallery is the part people skip.',
        photo: 'peshawar-museum-exp-2',
        signals: { photo: true, visitDetails: false, confirmed: true },
      },
      {
        id: 'x3',
        authorId: 'm6',
        when: '2 months ago',
        rating: 3.5,
        body: 'Worth the visit, though the lighting in the upper galleries has not been updated in decades.',
        photo: 'peshawar-museum-exp-3',
        signals: { photo: false, visitDetails: true, confirmed: true },
      },
    ],
    seal: null,
  },
];

export const defaultPlaceId = 'khyber-restaurant';

export const searchPlaceholder = 'Search places, people or experiences…';

/** OSM requires visible attribution wherever its tiles are displayed. */
export const placeCopy = {
  peopleYouKnow: 'People you know',
  visitedRecently: 'visited recently',
  seeTheirReviews: 'See their reviews',
  experiences: 'Experiences',
  seeAll: 'See all',
  experienceDetails: 'Experience details',
  writeYourExperience: 'Write Your Experience',
  savePlace: 'Save Place',
  saved: 'Saved',
  signalsNote: 'These signals indicate a genuine experience.',
  yourCircle: 'Your Circle',
};

export const signalLabels = {
  photo: 'Photo included',
  visitDetails: 'Visit details available',
  confirmed: 'Place confirmed',
};

/** @type {import('./types').CircleActivity[]} */
export const circleActivities = [
  {
    id: 'ca1',
    memberId: 'm1',
    verb: 'visited',
    placeId: 'khyber-restaurant',
    placeName: 'Khyber Restaurant',
    headline: 'The charcoal grill',
    time: '2 days ago',
    quote: 'The chapli kebab here is exceptional.',
    tone: 'berry',
    icon: 'silverware-fork-knife',
    photo: 'khyber-restaurant-hero-1',
  },
  {
    id: 'ca2',
    memberId: 'm2',
    verb: 'saved',
    placeId: 'cafe-qahwa',
    placeName: 'Café Qahwa',
    headline: 'Beans worth taking home',
    time: '4 days ago',
    quote: 'They will sell you a bag of what they are pouring.',
    tone: 'gold',
    icon: 'bookmark',
    photo: 'cafe-qahwa-hero-2',
  },
  {
    id: 'ca3',
    memberId: 'm3',
    verb: 'reviewed',
    placeId: 'beanstalk-coffee',
    placeName: 'Beanstalk Coffee',
    headline: 'Best courtyard in Hayatabad',
    time: 'Yesterday',
    quote: 'Quiet enough to take a call, which is rare here.',
    tone: 'berry',
    icon: 'star',
    photo: 'beanstalk-coffee-hero-1',
  },
  {
    id: 'ca4',
    memberId: 'm4',
    verb: 'liked Bilal’s review of',
    placeId: 'bala-bagh-fort',
    placeName: 'Bala Bagh Fort',
    headline: 'Go at dusk',
    time: '3 days ago',
    quote: 'The light through the eastern arch is worth the climb.',
    tone: 'rose',
    icon: 'heart',
    photo: 'bala-bagh-fort-hero-3',
  },
  {
    id: 'ca5',
    memberId: 'm5',
    verb: 'verified',
    placeId: 'khyber-restaurant',
    placeName: 'Khyber Restaurant',
    headline: 'Cash only, still true',
    time: 'Last week',
    quote: 'Confirmed at the door on Saturday evening.',
    tone: 'sand',
    icon: 'shield-check',
    photo: 'khyber-restaurant-hero-4',
  },
  {
    id: 'ca6',
    memberId: 'm6',
    verb: 'visited',
    placeId: 'qissa-khwani-bazaar',
    placeName: 'Qissa Khwani Bazaar',
    headline: 'Go before eleven',
    time: '2 weeks ago',
    quote: 'The dry fruit stalls at the far end are the reason.',
    tone: 'gold',
    icon: 'shopping-outline',
    photo: 'qissa-khwani-bazaar-hero-2',
  },
  {
    id: 'ca7',
    memberId: 'm7',
    verb: 'added a photo to',
    placeId: 'cheezious-usmanzai',
    placeName: 'Cheezious',
    headline: 'The queue at 8pm',
    time: '3 weeks ago',
    quote: 'Worth every minute, as always.',
    tone: 'rose',
    icon: 'image-plus',
    photo: 'cheezious-usmanzai-hero-1',
  },
  {
    id: 'ca8',
    memberId: 'm8',
    verb: 'joined your Circle',
    placeId: '',
    placeName: '',
    headline: 'Invited by Bilal',
    time: 'Last month',
    quote: 'Met at the university road coffee run.',
    tone: 'sand',
    icon: 'account-plus',
    photo: 'peshawar-museum-hero-2',
  },
];

export const circleCopy = {
  eyebrow: 'Your circle',
  title: 'Circle',
  subtitle: 'People you trust, and the moments they share with you.',
  addPerson: 'Add someone to your Circle',
  peopleInCircle: 'in your Circle',
  seeAll: 'See all',
  recentActivity: 'Recent activity',
  searchPlaceholder: 'Find someone in your circle…',
  invited: 'Invite',
};
